### ISSUE TITLE
[Docker]- Docker Compose 

### ISSUE THREAD

**Issue by apoorvpandey-ap** [apoorvpandey-ap/-devops-interview-question#29]
Reference Link  -https://github.com/apoorvpandey-ap/Docker/issues/1
### **Step-4** UP the docker compose
`docker-compose -f docker-compose.yml up -d`
#
## YML file save as `docker-compose`
```
version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kakfa
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
```
#
![image](https://user-images.githubusercontent.com/66588814/158158471-f768568f-8948-41ea-a04c-d5dab7ee819b.png)
